[package]
name = "lexicon"
version = "1.0.0"
edition = "2021"
authors = ["alexander14k"]

[dependencies]
# no other libs used

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = "debuginfo"
codegen-units = 1
rpath = false
